---
- name: Install Docker on EC2 Instances
  hosts: backend, database, frontend
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.yum:
        update_cache: yes

    - name: Install required packages (Docker)
      ansible.builtin.yum:
        name:
          - docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
